// apps/vue-app/src/app/components/WeeklyView.vue
<template>
  <div class="flex flex-col items-start justify-start gap-3 p-5">
    <span> Weekly </span>

    <NxCalendarHeatmap
      :options="options"
      :heatmap-data="heatmapData"
      class="p-4 border border-gray-500 rounded-md dark:bg-gray-800"
    />
  </div>
</template>

<script setup lang="ts">
import { NxCalendarHeatmap } from '@ngeenx/nx-vue-calendar-heatmap';
import {
  IHeatmapDay,
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  HeatmapLevelsDirection,
} from '@ngeenx/nx-calendar-heatmap-utils';
import { DateTime } from 'luxon';
import { onMounted, ref, watch } from 'vue';

/**
 * Component props
 */
const props = defineProps({
  selectedColorVariant: {
    type: Array as () => IHeatmapColor[],
    default: () => [],
  },
  selectedYear: {
    type: Number,
    default: () => {
      return DateTime.now().year;
    },
  },
  selectedHeatmapLevelState: {
    type: Boolean,
    default: () => {
      return true;
    },
  },
  selectedLocale: {
    type: String,
    default: () => {
      return 'en';
    },
  },
});

const startDate = ref(DateTime.now().startOf('year'));
const heatmapData = ref<IHeatmapDay[]>([]);

const onDayClick = (day: IHeatmapDay) => {
  console.log(`Clicked on ${day.date} with value ${day.count}`);
};

const options = ref<ICalendarHeatmapOptions>({
  type: HeatMapCalendarType.WEEKLY,
  startDate: startDate.value,
  cellSize: 15,
  hideEmptyDays: false,
  colors: props.selectedColorVariant,
  onClick: onDayClick,
  tippyProps: {
    placement: 'bottom',
  },
  heatmapLegend: {
    direction: HeatmapLevelsDirection.LEFT,
  },
});

const generateHeatmapData = (startDate: DateTime) => {
  let endDate: DateTime = startDate.plus({ days: 6 });

  const daysBetween = Math.floor(endDate.diff(startDate, 'days').days);
  const heatmap = [];

  let currentDate = startDate;

  for (let i = 0; i <= daysBetween; i++) {
    const day: IHeatmapDay = {
      date: currentDate,
      count: Math.floor(Math.random() * 101),
    };

    heatmap.push(day);

    currentDate = currentDate.plus({ days: 1 });
  }

  return heatmap;
};

watch(
  () => [
    props.selectedColorVariant,
    props.selectedYear,
    props.selectedHeatmapLevelState,
    props.selectedLocale,
  ],
  () => {
    options.value = {
      ...options.value,
      colors: props.selectedColorVariant,
      startDate: startDate.value,
      locale: props.selectedLocale,
      heatmapLegend: {
        ...options.value.heatmapLegend,
        display: props.selectedHeatmapLevelState,
      },
    };

    startDate.value = DateTime.fromJSDate(
      new Date(`${props.selectedYear}-01-01`)
    ) as any;

    heatmapData.value = generateHeatmapData(startDate.value);
  }
);
onMounted(() => {
  heatmapData.value = generateHeatmapData(startDate.value);
});
</script>

// apps/angular-app/src/app/components/weekly-view/weekly-view.component.ts
import { Component, Input, OnChanges, OnInit } from "@angular/core";
import { NxHeatmapCalendarComponent } from "@ngeenx/nx-angular-calendar-heatmap";
import {
  IHeatmapColor,
  IHeatmapDay,
  ICalendarHeatmapOptions,
  HeatMapCalendarType,
  HeatmapLevelsDirection,
} from "@ngeenx/nx-calendar-heatmap-utils";
import { DateTime } from "luxon";

@Component({
  selector: "app-weekly-view",
  templateUrl: "./weekly-view.component.html",
  standalone: true,
  imports: [NxHeatmapCalendarComponent],
})
export class WeeklyViewComponent implements OnInit, OnChanges {
  @Input() selectedColorVariant: IHeatmapColor[] = [];
  @Input() selectedYear: number = DateTime.now().year;
  @Input() selectedHeatmapLevelState = true;
  @Input() selectedLocale = "en";

  heatmapData: IHeatmapDay[] = [];
  options!: ICalendarHeatmapOptions;

  ngOnInit(): void {
    this.options = this.getOptions();

    this.generateHeatmapData();
  }

  ngOnChanges(): void {
    this.options = this.getOptions();

    this.generateHeatmapData();
  }

  private generateHeatmapData(): void {
    const startDate = DateTime.fromObject({
      year: this.selectedYear,
      month: 1,
      day: 1,
    });
    const endDate = startDate.plus({ days: 6 });

    const daysBetween = Math.floor(endDate.diff(startDate, "days").days);
    this.heatmapData = [];

    let currentDate = startDate;

    for (let i = 0; i <= daysBetween; i++) {
      const day: IHeatmapDay = {
        date: currentDate,
        count: Math.floor(Math.random() * 101), // Random count for demonstration
      };
      this.heatmapData.push(day);
      currentDate = currentDate.plus({ days: 1 });
    }
  }

  onDayClick(day: IHeatmapDay): void {
    console.log(`Clicked on ${day.date.toISODate()} with value ${day.count}`);
  }

  public getOptions(): ICalendarHeatmapOptions {
    return {
      type: HeatMapCalendarType.WEEKLY,
      cellSize: 15,
      hideEmptyDays: false,
      colors: this.selectedColorVariant,
      onClick: this.onDayClick,
      tippyProps: {
        placement: "bottom",
      },
      heatmapLegend: {
        direction: HeatmapLevelsDirection.LEFT,
        display: this.selectedHeatmapLevelState,
      },
      locale: this.selectedLocale,
    } as ICalendarHeatmapOptions;
  }
}

<div class="flex flex-col items-start justify-start gap-3 p-5">
  <span>Weekly</span>
  <nx-heatmap-calendar
    [options]="options"
    [heatmapData]="heatmapData"
    class="p-4 border border-gray-500 rounded-md dark:bg-gray-800"
  ></nx-heatmap-calendar>
</div>
