// apps/angular-app/src/app/components/monthly-view/monthly-view.component.ts
import { Component, Input, OnChanges, OnInit } from "@angular/core";
import { NxCalendarHeatmapComponent } from "@ngeenx/nx-angular-calendar-heatmap";
import {
  IHeatmapColor,
  IHeatmapDay,
  ICalendarHeatmapOptions,
  HeatMapCalendarType,
  HeatmapLevelsDirection,
} from "@ngeenx/nx-calendar-heatmap-utils";
import { DateTime } from "luxon";

@Component({
  selector: "app-monthly-view",
  templateUrl: "./monthly-view.component.html",
  imports: [NxCalendarHeatmapComponent],
  standalone: true,
})
export class MonthlyViewComponent implements OnInit, OnChanges {
  @Input() selectedColorVariant: IHeatmapColor[] = [];
  @Input() selectedYear: number = DateTime.now().year;
  @Input() selectedHeatmapLevelState = true;
  @Input() selectedLocale = "en";

  months: DateTime[] = [];
  heatmapData: IHeatmapDay[][] = [];
  options: ICalendarHeatmapOptions;
  public calendars: any[] = [];

  constructor() {
    this.options = this.getOptions();
  }

  ngOnInit(): void {
    this.generateHeatmapDataForYear();
  }

  ngOnChanges(): void {
    this.options = this.getOptions();

    this.generateHeatmapDataForYear();
  }

  private generateHeatmapDataForYear(): void {
    this.months = Array.from({ length: 12 }, (_, i) =>
      DateTime.local().set({ year: this.selectedYear, month: i + 1, day: 1 })
    );

    this.heatmapData = this.months.map((monthStartDate) =>
      this.generateHeatmapData(monthStartDate)
    );

    this.calendars = this.heatmapData.map((monthData) => ({
      config: { ...this.options, startDate: monthData[0].date },
      data: monthData,
    }));
  }

  private generateHeatmapData(startDate: DateTime): IHeatmapDay[] {
    const endDate = startDate.endOf("month");
    const daysBetween = Math.floor(endDate.diff(startDate, "days").days);
    const monthData: IHeatmapDay[] = [];
    let currentDate = startDate;

    for (let i = 0; i <= daysBetween; i++) {
      const day: IHeatmapDay = {
        date: currentDate,
        count: Math.floor(Math.random() * 101), // Random count for demonstration
      };
      monthData.push(day);
      currentDate = currentDate.plus({ days: 1 });
    }
    return monthData;
  }

  private onDayClick(day: IHeatmapDay): void {
    console.log(`Clicked on ${day.date.toISODate()} with value ${day.count}`);
  }

  private getOptions(): any {
    return {
      type: HeatMapCalendarType.MONTHLY,
      cellSize: 15,
      hideEmptyDays: false,
      colors: this.selectedColorVariant,
      heatmapLegend: {
        display: this.selectedHeatmapLevelState,
        direction: HeatmapLevelsDirection.RIGHT,
      },
      overWritedDayStyle: { borderRadius: "50%" },
      locale: this.selectedLocale,
      onClick: (day: IHeatmapDay) => this.onDayClick(day),
    };
  }
}

<div class="flex flex-col items-start justify-start gap-3 p-5">
  <span>Monthly</span>
  <div
    class="flex flex-row flex-wrap gap-5 p-4 bg-white border border-gray-500 rounded-md dark:bg-gray-800"
  >
    @for (calendar of calendars; track $index) {
    <nx-heatmap-calendar
      [options]="calendar.config"
      [heatmapData]="calendar.data"
      class="p-4 border border-gray-500 rounded-md"
    ></nx-heatmap-calendar>
    }
  </div>
</div>

// apps/vue-app/src/app/components/MonthlyView.vue
<template>
  <div class="flex flex-col items-start justify-start gap-3 p-5">
    <span> Monthly </span>

    <div
      class="flex flex-row flex-wrap gap-5 p-4 bg-white rounded-md dark:bg-gray-800"
    >
      <NxCalendarHeatmap
        v-for="(_heatmapDataMonthly, index) in heatmapData"
        :key="index"
        :options="{
          ...options,
          startDate: months[index],
        }"
        :heatmap-data="_heatmapDataMonthly"
        class="p-4 border border-gray-500 rounded-md"
      />
    </div>
  </div>
</template>

<script setup lang="ts">
import { NxCalendarHeatmap } from '@ngeenx/nx-vue-calendar-heatmap';
import {
  IHeatmapDay,
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  HeatmapLevelsDirection,
} from '@ngeenx/nx-calendar-heatmap-utils';
import { DateTime } from 'luxon';
import { onMounted, ref, watch } from 'vue';

/**
 * Component props
 */
const props = defineProps({
  selectedColorVariant: {
    type: Array as () => IHeatmapColor[],
    default: () => [],
  },
  selectedYear: {
    type: Number,
    default: () => {
      return DateTime.now().year;
    },
  },
  selectedHeatmapLevelState: {
    type: Boolean,
    default: () => {
      return true;
    },
  },
});

const startDate = ref(DateTime.now().startOf('year'));
const heatmapData = ref<IHeatmapDay[][]>([]);

let months = Array.from(
  { length: 12 },
  (_, i): DateTime => DateTime.local().set({ month: i + 1, day: 1 })
);

const onDayClick = (day: IHeatmapDay) => {
  console.log(`Clicked on ${day.date} with value ${day.count}`);
};

const options = ref<ICalendarHeatmapOptions>({
  type: HeatMapCalendarType.MONTHLY,
  startDate: startDate.value,
  cellSize: 15,
  hideEmptyDays: false,
  colors: props.selectedColorVariant,
  onClick: onDayClick,
  heatmapLegend: {
    display: props.selectedHeatmapLevelState,
    direction: HeatmapLevelsDirection.RIGHT,
  },
  overWritedDayStyle: {
    borderRadius: '50%',
  },
  locale: 'en',
});

const generateHeatmapData = (startDate: DateTime) => {
  let endDate: DateTime = startDate.endOf('month');

  const daysBetween = Math.floor(endDate.diff(startDate, 'days').days);
  const heatmap = [];

  let currentDate = startDate;

  for (let i = 0; i <= daysBetween; i++) {
    const day: IHeatmapDay = {
      date: currentDate,
      count: Math.floor(Math.random() * 101),
    };

    heatmap.push(day);

    currentDate = currentDate.plus({ days: 1 });
  }

  return heatmap;
};

watch(
  () => props.selectedYear,
  () => {
    startDate.value = DateTime.fromJSDate(
      new Date(`${props.selectedYear}-01-01`)
    ) as any;

    options.value = {
      ...options.value,
      startDate: startDate.value,
    };

    months = Array.from(
      { length: 12 },
      (_, i): DateTime =>
        DateTime.local().set({
          year: Number(props.selectedYear),
          month: i + 1,
          day: 1,
        })
    );

    heatmapData.value = months.map((firstDayOfMonth: DateTime) => {
      return generateHeatmapData(firstDayOfMonth);
    });
  }
);

watch(
  () => props.selectedColorVariant,
  () => {
    options.value = {
      ...options.value,
      colors: props.selectedColorVariant,
    };
  }
);

watch(
  () => props.selectedHeatmapLevelState,
  () => {
    options.value = {
      ...options.value,
      heatmapLegend: {
        ...options.value.heatmapLegend,
        display: props.selectedHeatmapLevelState,
      },
    };
  }
);

onMounted(() => {
  heatmapData.value = months.map((firstDayOfMonth: DateTime) => {
    return generateHeatmapData(firstDayOfMonth);
  });
});
</script>
