// apps/angular-app/src/app/components/yearly-view/yearly-view.component.ts
import { Component, Input, OnChanges, OnInit } from "@angular/core";
import { NxHeatmapCalendarComponent } from "@ngeenx/nx-angular-calendar-heatmap";
import {
  IHeatmapDay,
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  HeatmapLevelsDirection,
} from "@ngeenx/nx-calendar-heatmap-utils";
import { DateTime } from "luxon";

@Component({
  selector: "app-yearly-view",
  templateUrl: "./yearly-view.component.html",
  standalone: true,
  imports: [NxHeatmapCalendarComponent],
})
export class YearlyViewComponent implements OnInit, OnChanges {
  @Input() selectedColorVariant: IHeatmapColor[] = [];
  @Input() selectedYear: number = DateTime.now().year;
  @Input() selectedHeatmapLevelState = true;
  @Input() selectedLocale = "en";

  startDate: DateTime = DateTime.now().startOf("year");
  heatmapData: IHeatmapDay[] = [];
  options: ICalendarHeatmapOptions;

  constructor() {
    this.options = this.getOptions();
  }

  ngOnInit(): void {
    this.heatmapData = this.generateHeatmapData(this.startDate);
  }

  ngOnChanges(): void {
    this.startDate = DateTime.fromObject({ year: this.selectedYear }).startOf(
      "year"
    );
    this.heatmapData = this.generateHeatmapData(this.startDate);

    this.options = this.getOptions();
  }

  public onDayClick(day: IHeatmapDay): void {
    console.log(`Clicked on ${day.date.toISODate()} with value ${day.count}`);
  }

  private generateHeatmapData(startDate: DateTime): IHeatmapDay[] {
    const endDate = startDate.endOf("year");
    const daysBetween = Math.floor(endDate.diff(startDate, "days").days);
    const heatmap: IHeatmapDay[] = [];

    let currentDate = startDate;

    for (let i = 0; i <= daysBetween; i++) {
      const day: IHeatmapDay = {
        date: currentDate,
        count: Math.floor(Math.random() * 101),
      };

      heatmap.push(day);

      currentDate = currentDate.plus({ days: 1 });
    }

    return heatmap;
  }

  private getOptions(): ICalendarHeatmapOptions {
    return {
      type: HeatMapCalendarType.YEARLY,
      startDate: this.startDate,
      cellSize: 15,
      hideEmptyDays: false,
      locale: this.selectedLocale,
      colors: this.selectedColorVariant,
      heatmapLegend: {
        display: this.selectedHeatmapLevelState,
        direction: HeatmapLevelsDirection.RIGHT,
      },
      onClick: (day: IHeatmapDay) => this.onDayClick(day),
    };
  }
}

<div class="flex flex-col items-start justify-start gap-3 p-5">
  <span>Yearly</span>

  <nx-heatmap-calendar
    [options]="options"
    [heatmapData]="heatmapData"
    class="p-4 border border-gray-500 rounded-md dark:bg-gray-800"
  >
    <ng-template #footerContent>
      <a href="#" class="text-blue-400">Learn how we count contributions</a>
    </ng-template>
  </nx-heatmap-calendar>
</div>

// apps/vue-app/src/app/components/YearlyView.vue
<template>
  <div class="flex flex-col items-start justify-start gap-3 p-5">
    <span> Yearly </span>

    <NxCalendarHeatmap
      :options="options"
      :data="heatmapData"
      class="p-4 border border-gray-500 rounded-md dark:bg-gray-800"
    >
      <template #footerContent>
        <a href="#" class="text-blue-400"> Learn how we count contributions </a>
      </template>
    </NxCalendarHeatmap>
  </div>
</template>

<script setup lang="ts">
// vue
import { onMounted, ref, watch } from 'vue';

// libs
import { NxCalendarHeatmap } from '@ngeenx/nx-vue-calendar-heatmap';
import {
  IHeatmapDay,
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  HeatmapLevelsDirection,
} from '@ngeenx/nx-calendar-heatmap-utils';

// third party
import { DateTime } from 'luxon';

/**
 * Component props
 */
const props = defineProps({
  selectedColorVariant: {
    type: Array as () => IHeatmapColor[],
    default: () => [],
  },
  selectedYear: {
    type: Number,
    default: () => {
      return DateTime.now().year;
    },
  },
  selectedHeatmapLevelState: {
    type: Boolean,
    default: () => {
      return true;
    },
  },
  selectedLocale: {
    type: String,
    default: () => {
      return 'en';
    },
  },
});

const startDate = ref(DateTime.now().startOf('year'));
const heatmapData = ref<IHeatmapDay[]>([]);

const onDayClick = (day: IHeatmapDay) => {
  console.log(`Clicked on ${day.date} with value ${day.count}`);
};

const options = ref<ICalendarHeatmapOptions>({
  type: HeatMapCalendarType.YEARLY,
  startDate: startDate.value,
  cellSize: 15,
  hideEmptyDays: false,
  locale: props.selectedLocale,
  colors: props.selectedColorVariant,
  heatmapLegend: {
    display: props.selectedHeatmapLevelState,
    direction: HeatmapLevelsDirection.RIGHT,
  },
  onClick: onDayClick,
});

const generateHeatmapData = (startDate: DateTime) => {
  let endDate: DateTime = startDate.endOf('year');

  const daysBetween = Math.floor(endDate.diff(startDate, 'days').days);
  const heatmap = [];

  let currentDate = startDate;

  for (let i = 0; i <= daysBetween; i++) {
    const day: IHeatmapDay = {
      date: currentDate,
      count: Math.floor(Math.random() * 101),
    };

    heatmap.push(day);

    currentDate = currentDate.plus({ days: 1 });
  }

  return heatmap;
};

watch(
  () => [
    props.selectedYear,
    props.selectedColorVariant,
    props.selectedHeatmapLevelState,
    props.selectedLocale,
  ],
  () => {
    startDate.value = DateTime.fromJSDate(
      new Date(`${props.selectedYear}-01-01`)
    ) as any;

    heatmapData.value = generateHeatmapData(startDate.value);

    options.value = {
      ...options.value,
      startDate: startDate.value,
      colors: props.selectedColorVariant,
      locale: props.selectedLocale,
      heatmapLegend: {
        ...options.value.heatmapLegend,
        display: props.selectedHeatmapLevelState,
      },
    };
  }
);

onMounted(() => {
  heatmapData.value = generateHeatmapData(startDate.value);
});
</script>
