// libs/features/nx-vue-calendar-heatmap/src/components/NxCalendarHeatmap.vue
<template>
  <!-- Calendar Container -->
  <div class="nx-calendar-heatmap">
    <!-- Body -->
    <div class="body">
      <div class="weekdays-container">
        <!-- Weekdays -->
        <div
          v-if="mergedOptions.type !== HeatMapCalendarType.WEEKLY"
          class="weekdays"
        >
          <span
            v-for="(weekday, index) in mergedOptions.i18n?.weekdays"
            :key="index"
          >
            {{ weekday }}
          </span>
        </div>

        <!-- Months -->
        <div class="months-container">
          <!-- Yearly -->
          <div
            v-if="mergedOptions.type === HeatMapCalendarType.YEARLY"
            class="months"
          >
            <span
              v-for="(month, index) of mergedOptions.i18n?.months"
              :key="index"
            >
              {{ month }}
            </span>
          </div>

          <!-- Monthly -->
          <div
            v-if="mergedOptions.type === HeatMapCalendarType.MONTHLY"
            class="months"
          >
            <span class="centered">
              {{
                calendarUtils.getLocalizedMonthName(
                  mergedOptions.startDate,
                  mergedOptions.locale
                )
              }}
            </span>
          </div>

          <!-- Calendar Grid -->
          <div
            class="heatmap-grid"
            :class="{
              monthly: mergedOptions.type === HeatMapCalendarType.MONTHLY,
            }"
          >
            <!-- First Week Empty Days -->
            <template v-if="!mergedOptions.hideEmptyDays">
              <button
                v-for="(day, index) in firstWeekOffsetDays"
                :key="index"
                class="day"
                :class="getEmptyDayClass()"
                :style="emptyCellStyle"
                @mouseover="onDayMouseOver($event, day)"
              />
            </template>

            <!-- Available Days -->
            <button
              v-for="(day, index) in heatmapData"
              :key="index"
              class="day"
              :class="getDayClass(day.count)"
              :style="getGridPosition(index)"
              @click="onDayClick(day)"
              @mouseover="onDayMouseOver($event, day)"
            />

            <!-- Last Week Empty Days -->
            <template v-if="!mergedOptions.hideEmptyDays">
              <button
                v-for="(day, index) in lastWeekOffsetDays"
                :key="index"
                class="day"
                :class="getEmptyDayClass()"
                :style="emptyCellStyle"
                @mouseover="onDayMouseOver($event, day)"
              />
            </template>
          </div>
        </div>
      </div>
    </div>

    <!-- Footer -->
    <div v-if="mergedOptions.heatmapLegend?.display" class="footer">
      <!-- Footer Content -->
      <div class="footer-content">
        <slot name="footerContent" />
      </div>

      <div class="legend">
        <!-- Heatmap Legend -->
        <NxHeatmapLegend
          :options="mergedOptions"
          :min="min"
          :max="max"
          :range="range"
          :step="step"
          :levels="levels"
        />
      </div>
    </div>
  </div>
</template>

<script lang="ts" setup>
// vue
import { ref, watch, computed, StyleValue, onUnmounted, onMounted } from 'vue';

// libs
import {
  ICalendarHeatmapOptions,
  IHeatmapDay,
  HeatMapCalendarType,
  IHeatmapColor,
  DayTippyUtils,
  HeatmapLevelsDirection,
  CalendarUtils,
} from '@ngeenx/nx-calendar-heatmap-utils';
import NxHeatmapLegend from './NxHeatmapLegend.vue';

// third party
import { DateTime } from 'luxon';
import { Props } from 'tippy.js';

const levels = ref(5);
const min = ref(0);
const max = ref(0);
const range = ref(0);
const step = ref(0);
const heatmapData = computed<IHeatmapDay[]>(() => props.heatmapData || []);
const firstWeekOffsetDays = ref<IHeatmapDay[]>([]);
const lastWeekOffsetDays = ref<IHeatmapDay[]>([]);
const emptyCellStyle = ref<StyleValue>();

const defaultOptions: ICalendarHeatmapOptions = {
  type: HeatMapCalendarType.YEARLY,
  startDate: DateTime.now().startOf('year'),
  locale: 'en',
  tooltip: {
    display: true,
    unit: 'contribution',
    dateFormat: 'MMMM d',
  },
  tippyProps: {
    placement: 'top',
  } as Props,
  heatmapLegend: {
    display: true,
    direction: HeatmapLevelsDirection.RIGHT,
  },
  i18n: {
    weekdays: ['Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat', 'Sun'],
    on: 'on',
    less: 'less',
    more: 'more',
    noData: 'No',
    min: 'min',
    max: 'max',
  },
};

let tippyUtils!: DayTippyUtils;
let calendarUtils: CalendarUtils = new CalendarUtils(defaultOptions);

defaultOptions.i18n!.months = calendarUtils.getLocalizedMonthNames();
defaultOptions.i18n!.weekdays = calendarUtils.getLocalizedWeekdayNames();

/**
 * Component props
 */
const props = defineProps({
  options: {
    type: Object as () => ICalendarHeatmapOptions,
    default: () => ({}),
  },
  heatmapData: {
    type: Array as () => IHeatmapDay[],
    default: () => [],
  },
});

const mergedOptions = computed((): ICalendarHeatmapOptions => {
  return {
    ...defaultOptions,
    ...props.options,
    i18n: {
      ...defaultOptions.i18n,
      ...props.options.i18n,
    },
    heatmapLegend: {
      ...defaultOptions.heatmapLegend,
      ...props.options.heatmapLegend,
    },
    tooltip: {
      ...defaultOptions.tooltip,
      ...props.options.tooltip,
    },
  };
});

// #region Styling

/**
 * Grid position calculation depending on format
 *
 * @param index
 */
const getGridPosition = (index: number): StyleValue => {
  return calendarUtils.getGridPositionOfDay(
    index,
    firstWeekOffsetDays.value.length
  ) as StyleValue;
};

/**
 * Get the class name of a day based on its value with leveled classes
 *
 * @param value - The value of the day
 */
const getDayClass = (value: number | undefined): string => {
  const baseClasses = `${mergedOptions.value.onClick ? 'clickable' : ''}`;

  // if we are using default colors
  if (!mergedOptions.value.colors?.length) {
    if (value === 0 || value === undefined) {
      return `${baseClasses} level-0`;
    }

    for (let i = 0; i < levels.value; i++) {
      if (value <= min.value + step.value * (i + 1)) {
        return `${baseClasses} level-${i + 1}`;
      }
    }

    return `${baseClasses} level-0`;
  }

  // if we are using custom colors and value is not undefined (empty days values are undefined)
  if (value !== undefined) {
    for (const color of mergedOptions.value.colors) {
      if (color.min && color.max && value >= color.min && value <= color.max) {
        return color.className;
      }
    }
  }

  // find default color
  const defaultColor =
    mergedOptions.value.colors?.find(
      (color: IHeatmapColor) => color.isDefault
    ) || mergedOptions.value.colors?.[0];

  if (defaultColor) {
    return defaultColor.className;
  }

  return `${baseClasses} level-0`;
};

/**
 * Get the class name of an empty day based on its value with leveled classes
 */
const getEmptyDayClass = (): string => {
  if (!mergedOptions.value.colors?.length) {
    return 'level-0';
  }

  for (const color of mergedOptions.value.colors) {
    if (color.isDefault) {
      return color.className;
    }
  }

  return 'level-0';
};

// #endregion

// #region Events

/**
 * Handle day click event
 *
 * @param day - The day to click
 */
const onDayClick = (day: IHeatmapDay): void => {
  if (mergedOptions.value.onClick !== undefined) {
    mergedOptions.value.onClick(day);
  }
};

/**
 * Handle day mouse over event for tippy tooltip
 *
 * @param $event - The mouse event
 * @param day - The day to show tooltip for
 */
const onDayMouseOver = ($event: MouseEvent, day: IHeatmapDay): void => {
  tippyUtils?.lazyLoadTooltip($event, day);
};

// #endregion

/**
 * Update the heatmap data based on the options
 */
const updateHeatmapData = (): void => {
  calendarUtils = new CalendarUtils(mergedOptions.value);
  defaultOptions.i18n!.months = calendarUtils.getLocalizedMonthNames(
    mergedOptions.value.locale
  );
  mergedOptions.value.i18n!.months = calendarUtils.getLocalizedMonthNames(
    mergedOptions.value.locale
  );
  defaultOptions.i18n!.weekdays = calendarUtils.getLocalizedWeekdayNames(
    mergedOptions.value.locale
  );
  mergedOptions.value.i18n!.weekdays = calendarUtils.getLocalizedWeekdayNames(
    mergedOptions.value.locale
  );

  emptyCellStyle.value = {
    height: (mergedOptions.value.cellSize || 15) + 'px',
    width: (mergedOptions.value.cellSize || 15) + 'px',
    ...mergedOptions.value.overWritedDayStyle,
  };

  if (mergedOptions.value.colors?.length) {
    levels.value = mergedOptions.value.colors.length;
  } else {
    levels.value = 5;
  }

  min.value = 0;
  max.value = 100;
  range.value = max.value - min.value;
  step.value = range.value / levels.value;

  const { type, startDate } = mergedOptions.value;

  let endDate: DateTime;

  switch (type) {
    case HeatMapCalendarType.WEEKLY:
      // weekly, only 7 days
      endDate = startDate.plus({ days: 6 });

      break;
    case HeatMapCalendarType.MONTHLY:
      // monthly, all days of the month
      endDate = startDate.endOf('month');

      break;
    case HeatMapCalendarType.YEARLY:
      // yearly, full year
      endDate = startDate.endOf('year');

      break;
  }

  if (type !== HeatMapCalendarType.WEEKLY) {
    firstWeekOffsetDays.value =
      calendarUtils.calculateFirstWeekOffset(startDate);
    lastWeekOffsetDays.value = calendarUtils.calculateLastWeekOffset(endDate);
  }
};

/**
 * Watch for changes in the options and update the heatmap data
 */
watch(() => mergedOptions.value, updateHeatmapData, { immediate: true });

onMounted(() => {
  // tippy utils
  tippyUtils = new DayTippyUtils(mergedOptions.value);
  tippyUtils.init();

  emptyCellStyle.value = {
    ...mergedOptions.value.overWritedDayStyle,
  };
});

onUnmounted(() => {
  tippyUtils?.destroy();
});
</script>

// libs/features/nx-angular-calendar-heatmap/src/lib/components/nx-calendar-heatmap/nx-calendar-heatmap.component.ts
import { Component, Input, OnInit, OnDestroy } from "@angular/core";
import { CommonModule } from "@angular/common";
import { DateTime } from "luxon";
import {
  ICalendarHeatmapOptions,
  IHeatmapDay,
  HeatMapCalendarType,
  IHeatmapColor,
  DayTippyUtils,
  HeatmapLevelsDirection,
  CalendarUtils,
} from "@ngeenx/nx-calendar-heatmap-utils";
import { NxHeatmapCalendarLegendComponent } from "../nx-calendar-legend/nx-calendar-legend.component";

const defaultOptions: ICalendarHeatmapOptions = {
  type: HeatMapCalendarType.YEARLY,
  startDate: DateTime.now().startOf("year"),
  locale: "en",
  tooltip: {
    display: true,
    unit: "contribution",
    dateFormat: "MMMM d",
  },
  tippyProps: { placement: "top" },
  heatmapLegend: {
    display: true,
    direction: HeatmapLevelsDirection.RIGHT,
  },
  i18n: {
    weekdays: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"],
    months: [],
    on: "on",
    less: "less",
    more: "more",
    noData: "No",
    min: "min",
    max: "max",
  },
};

@Component({
  imports: [CommonModule, NxHeatmapCalendarLegendComponent],
  selector: "nx-heatmap-calendar",
  templateUrl: "./nx-calendar-heatmap.component.html",
  standalone: true,
})
export class NxHeatmapCalendarComponent implements OnInit, OnDestroy {
  @Input() options: ICalendarHeatmapOptions = {} as ICalendarHeatmapOptions;
  @Input() heatmapData: IHeatmapDay[] = [];

  public HeatMapCalendarType: typeof HeatMapCalendarType = HeatMapCalendarType;

  levels = 5;
  min = 0;
  max = 0;
  range = 0;
  step = 0;

  emptyCellStyle: any = {} as any;

  mergedOptions: ICalendarHeatmapOptions = {} as ICalendarHeatmapOptions;
  firstWeekOffsetDays: IHeatmapDay[] = [];
  lastWeekOffsetDays: IHeatmapDay[] = [];
  calendarUtils = new CalendarUtils(defaultOptions);
  tippyUtils: DayTippyUtils | undefined;

  ngOnInit() {
    this.mergedOptions = { ...defaultOptions, ...this.options };
    this.updateHeatmapData();
    this.tippyUtils = new DayTippyUtils(this.mergedOptions);
    this.tippyUtils.init();
  }

  ngOnDestroy() {
    this.tippyUtils?.destroy();
  }

  updateHeatmapData() {
    this.calendarUtils = new CalendarUtils(this.mergedOptions);

    if (this.mergedOptions.i18n) {
      this.mergedOptions.i18n.months =
        this.calendarUtils.getLocalizedMonthNames(this.mergedOptions.locale);
      this.mergedOptions.i18n.weekdays =
        this.calendarUtils.getLocalizedWeekdayNames(this.mergedOptions.locale);
    }

    this.emptyCellStyle = {
      height: `${this.mergedOptions.cellSize || 15}px`,
      width: `${this.mergedOptions.cellSize || 15}px`,
      ...this.mergedOptions.overWritedDayStyle,
    };

    this.levels = this.mergedOptions.colors?.length || 5;
    this.range = 100;
    this.step = this.range / this.levels;

    const { type, startDate } = this.mergedOptions;
    let endDate;

    switch (type) {
      case HeatMapCalendarType.WEEKLY:
        endDate = startDate.plus({ days: 6 });
        break;
      case HeatMapCalendarType.MONTHLY:
        endDate = startDate.endOf("month");
        break;
      case HeatMapCalendarType.YEARLY:
        endDate = startDate.endOf("year");
        break;
    }

    if (type !== HeatMapCalendarType.WEEKLY) {
      this.firstWeekOffsetDays =
        this.calendarUtils.calculateFirstWeekOffset(startDate);
      this.lastWeekOffsetDays =
        this.calendarUtils.calculateLastWeekOffset(endDate);
    }
  }

  getGridPosition(index: number): object {
    return this.calendarUtils.getGridPositionOfDay(
      index,
      this.firstWeekOffsetDays.length
    );
  }

  getDayClass(value: number | undefined): string {
    const baseClasses = `${this.mergedOptions.onClick ? "clickable" : ""}`;

    if (!this.mergedOptions.colors?.length) {
      if (value === 0 || value === undefined) return `${baseClasses} level-0`;

      for (let i = 0; i < this.levels; i++) {
        if (value <= this.min + this.step * (i + 1))
          return `${baseClasses} level-${i + 1}`;
      }
      return `${baseClasses} level-0`;
    }

    if (value !== undefined) {
      for (const color of this.mergedOptions.colors) {
        if (color.min && color.max && value >= color.min && value <= color.max)
          return color.className;
      }
    }

    const defaultColor =
      this.mergedOptions.colors?.find(
        (color: IHeatmapColor) => color.isDefault
      ) || this.mergedOptions.colors?.[0];
    return defaultColor ? defaultColor.className : `${baseClasses} level-0`;
  }

  getEmptyDayClass(): string {
    const defaultColor = this.mergedOptions.colors?.find(
      (color) => color.isDefault
    ) || { className: "level-0" };
    return defaultColor.className;
  }

  onDayClick(day: IHeatmapDay) {
    if (this.mergedOptions.onClick) this.mergedOptions.onClick(day);
  }

  onDayMouseOver(event: MouseEvent, day: IHeatmapDay) {
    this.tippyUtils?.lazyLoadTooltip(event, day);
  }
}

<!-- eslint-disable @angular-eslint/template/mouse-events-have-key-events -->
<!-- Calendar Container -->
<div class="nx-calendar-heatmap">
  <!-- Body -->
  <div class="body">
    <div class="weekdays-container">
      <!-- Weekdays -->
      <div
        *ngIf="mergedOptions.type !== HeatMapCalendarType.WEEKLY"
        class="weekdays"
      >
        <span *ngFor="let weekday of mergedOptions.i18n?.weekdays">
          {{ weekday }}
        </span>
      </div>

      <!-- Months -->
      <div class="months-container">
        <!-- Yearly -->
        <div
          *ngIf="mergedOptions.type === HeatMapCalendarType.YEARLY"
          class="months"
        >
          <span *ngFor="let month of mergedOptions.i18n?.months">{{
            month
          }}</span>
        </div>

        <!-- Monthly -->
        <div
          *ngIf="mergedOptions.type === HeatMapCalendarType.MONTHLY"
          class="months"
        >
          <span class="centered">
            {{
              calendarUtils.getLocalizedMonthName(
                mergedOptions.startDate,
                mergedOptions.locale
              )
            }}
          </span>
        </div>

        <!-- Calendar Grid -->
        <div
          class="heatmap-grid"
          [ngClass]="{
            monthly: mergedOptions.type === HeatMapCalendarType.MONTHLY
          }"
        >
          <!-- First Week Empty Days -->
          <ng-container *ngIf="!mergedOptions.hideEmptyDays">
            <button
              *ngFor="let day of firstWeekOffsetDays"
              class="day"
              [ngClass]="getEmptyDayClass()"
              [ngStyle]="emptyCellStyle"
              (mouseover)="onDayMouseOver($event, day)"
            >
              <!-- Empty Day Button -->
            </button>
          </ng-container>

          <!-- Available Days -->
          <button
            *ngFor="let day of heatmapData; let i = index"
            class="day"
            [ngClass]="getDayClass(day.count)"
            [ngStyle]="getGridPosition(i)"
            (click)="onDayClick(day)"
            (mouseover)="onDayMouseOver($event, day)"
          >
            <!-- Day Button -->
          </button>

          <!-- Last Week Empty Days -->
          <ng-container *ngIf="!mergedOptions.hideEmptyDays">
            <button
              *ngFor="let day of lastWeekOffsetDays"
              class="day"
              [ngClass]="getEmptyDayClass()"
              [ngStyle]="emptyCellStyle"
              (mouseover)="onDayMouseOver($event, day)"
            >
              <!-- Empty Day Button -->
            </button>
          </ng-container>
        </div>
      </div>
    </div>
  </div>

  <!-- Footer -->
  <div *ngIf="mergedOptions.heatmapLegend?.display" class="footer">
    <div class="footer-content">
      <ng-content select="[footerContent]"></ng-content>
    </div>
    <div class="legend">
      <nx-heatmap-calendar-legend
        [options]="mergedOptions"
        [min]="min"
        [max]="max"
        [range]="range"
        [step]="step"
        [levels]="levels"
      ></nx-heatmap-calendar-legend>
    </div>
  </div>
</div>
