// apps/vue-app/src/app/components/WeeklyView.vue
<template>
  <div class="flex flex-col items-start justify-start gap-3 p-5">
    <span> Weekly </span>

    <NxCalendarHeatmap
      :options="options"
      :heatmap-data="heatmapData"
      class="p-4 border border-gray-500 rounded-md dark:bg-gray-800"
    />
  </div>
</template>

<script setup lang="ts">
import { NxCalendarHeatmap } from '@ngeenx/nx-vue-calendar-heatmap';
import {
  IHeatmapDay,
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  HeatmapLevelsDirection,
} from '@ngeenx/nx-calendar-heatmap-utils';
import { DateTime } from 'luxon';
import { onMounted, ref, watch } from 'vue';

/**
 * Component props
 */
const props = defineProps({
  selectedColorVariant: {
    type: Array as () => IHeatmapColor[],
    default: () => [],
  },
  selectedYear: {
    type: Number,
    default: () => {
      return DateTime.now().year;
    },
  },
  selectedHeatmapLevelState: {
    type: Boolean,
    default: () => {
      return true;
    },
  },
  selectedLocale: {
    type: String,
    default: () => {
      return 'en';
    },
  },
});

const startDate = ref(DateTime.now().startOf('year'));
const heatmapData = ref<IHeatmapDay[]>([]);

const onDayClick = (day: IHeatmapDay) => {
  console.log(`Clicked on ${day.date} with value ${day.count}`);
};

const options = ref<ICalendarHeatmapOptions>({
  type: HeatMapCalendarType.WEEKLY,
  startDate: startDate.value,
  cellSize: 15,
  hideEmptyDays: false,
  colors: props.selectedColorVariant,
  onClick: onDayClick,
  tippyProps: {
    placement: 'bottom',
  },
  heatmapLegend: {
    direction: HeatmapLevelsDirection.LEFT,
  },
});

const generateHeatmapData = (startDate: DateTime) => {
  let endDate: DateTime = startDate.plus({ days: 6 });

  const daysBetween = Math.floor(endDate.diff(startDate, 'days').days);
  const heatmap = [];

  let currentDate = startDate;

  for (let i = 0; i <= daysBetween; i++) {
    const day: IHeatmapDay = {
      date: currentDate,
      count: Math.floor(Math.random() * 101),
    };

    heatmap.push(day);

    currentDate = currentDate.plus({ days: 1 });
  }

  return heatmap;
};

watch(
  () => [
    props.selectedColorVariant,
    props.selectedYear,
    props.selectedHeatmapLevelState,
    props.selectedLocale,
  ],
  () => {
    options.value = {
      ...options.value,
      colors: props.selectedColorVariant,
      startDate: startDate.value,
      locale: props.selectedLocale,
      heatmapLegend: {
        ...options.value.heatmapLegend,
        display: props.selectedHeatmapLevelState,
      },
    };

    startDate.value = DateTime.fromJSDate(
      new Date(`${props.selectedYear}-01-01`)
    ) as any;

    heatmapData.value = generateHeatmapData(startDate.value);
  }
);
onMounted(() => {
  heatmapData.value = generateHeatmapData(startDate.value);
});
</script>

// apps/react-app/src/app/components/WeeklyView.tsx
import React, { useEffect, useState, useCallback } from 'react';
import { DateTime } from 'luxon';
import { NxCalendarHeatmap } from '@ngeenx/nx-react-calendar-heatmap';
import {
  HeatMapCalendarType,
  ICalendarHeatmapOptions,
  IHeatmapColor,
  IHeatmapDay,
} from '@ngeenx/nx-calendar-heatmap-utils';

interface WeeklyViewProps {
  selectedColorVariant?: IHeatmapColor[];
  selectedYear?: number;
  selectedHeatmapLevelState?: boolean;
  selectedLocale?: string;
}

const WeeklyHeatmap: React.FC<WeeklyViewProps> = ({
  selectedColorVariant = [],
  selectedYear = DateTime.now().year,
  selectedHeatmapLevelState = true,
  selectedLocale = 'en',
}) => {
  const [startDate, setStartDate] = useState<DateTime>(
    DateTime.now().startOf('year')
  );
  const [heatmapData, setHeatmapData] = useState<IHeatmapDay[]>([]);

  const options = {
    type: HeatMapCalendarType.WEEKLY,
    startDate,
    cellSize: 15,
    hideEmptyDays: false,
    colors: selectedColorVariant,
    tippyProps: {
      placement: 'bottom',
    },
    heatmapLegend: {
      display: selectedHeatmapLevelState,
      direction: 'LEFT',
    },
    locale: selectedLocale,
  } as object as ICalendarHeatmapOptions;

  const generateHeatmapData = useCallback((startDate: DateTime) => {
    const endDate = startDate.plus({ days: 6 });
    const daysBetween = Math.floor(endDate.diff(startDate, 'days').days);
    const heatmap = [];

    let currentDate = startDate;

    for (let i = 0; i <= daysBetween; i++) {
      heatmap.push({
        date: currentDate,
        count: Math.floor(Math.random() * 101),
      });
      currentDate = currentDate.plus({ days: 1 });
    }

    return heatmap;
  }, []);

  useEffect(() => {
    setStartDate(DateTime.local(selectedYear, 1, 1));

    setHeatmapData(generateHeatmapData(DateTime.local(selectedYear, 1, 1)));
  }, [
    selectedYear,
    selectedColorVariant,
    selectedHeatmapLevelState,
    selectedLocale,
    generateHeatmapData,
  ]);

  return (
    <div className="flex flex-col items-start justify-start gap-3 p-5">
      <span> Weekly </span>

      <div className="p-4 border border-gray-500 rounded-md dark:bg-gray-800">
        <NxCalendarHeatmap options={options} heatmapData={heatmapData} />
      </div>
    </div>
  );
};

export default WeeklyHeatmap;
